name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
        issue-message: 'Congrats! You just created a PR :heart: The maintainers will review soon'' first issue'
        pr-message: 'Congrats! You created your first PR on this repository :+1: We will revert shortly'' first pr'
© 2020 GitHub, Inc.
